{
 "title": "QALadies",
 "tags": [
  "jmeter",
  "performance",
  "qa"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jmeter_threads{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(rate(count_total[5m]))" }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(count_total)" }
   ]
  },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum((rate(fail_total[5m])))/sum((rate(count_total[5m])))"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Virtual users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Virtual Users vs  HTTP code ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_threads{exported_state=\"started\"})",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "sum by (code)(rate(count_total{code=~\"5.*|4.*\"}[5m]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Response times - average by sampler (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(latency_as_sum[5m])) by(label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests per second - Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(count_total[5m]))", "legendFormat": " " }
   ]
  },
  {
   "title": "Requests per second - by sampler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label) (rate(count_total[5m]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Requests per second - by HTTP code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code)(rate(count_total[5m]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "HTTP 4** 5** per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_total{code=~\"5.*|4.*\"}",
     "legendFormat": "{{label}} - HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Failure by assertion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "assertions_failure", "legendFormat": "{{label}}" }
   ]
  }
 ]
}